- name: ansible-playbook
  hosts: aws-fontend
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: setting git
      become: yes
      shell: apt update 
             apt install git
             git --version
    - name: setting java
      become: yes
      command: apt install default-jre
  #  - name: create a file 
  #    command: touch /home/ubuntu/newfile
  #  - name: create a new directory
  #    command: mkdir /home//newdirectory